### ISSUE TITLE
Redis连接被拒绝错误

### ISSUE THREAD

**Issue by poboll** [BlockG-ws/mxspace-z#1]
**问题描述：**
我在使用您的项目时遇到了一个问题，似乎无法连接到Redis服务器。我查看了日志文件，发现了以下错误信息：
```vbnet
08:35:59 ERROR [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
08:36:10 ERROR [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) (repeated 33 times)
```
程序无法连接到Redis服务器（位于127.0.0.1:6379）。这可能导致了一些功能无法正常工作。

**复现步骤：**
    fork并启动您的项目。
    查看项目日志文件或控制台输出。
![捕获](https://github.com/BlockG-ws/mxspace-z/assets/80184334/e8adedaa-8881-469e-9ccc-be32f3b3ed13)

**实际行为：**
程序尝试连接到Redis服务器，但无法成功，并抛出了上述错误。

**Comment by GrassBlock1** [comment]
https://github.com/BlockG-ws/mx-zcore v5.5.3 版本应该解决了此错误
此仓库将在不久后跟进更新
